### ISSUE TITLE
python v3.6.4版本下眼睛有一部分是蓝色的...

### ISSUE THREAD

**Issue by AomoriL** [PerpetualSmile/Python-painting-Doraemon#1]
![image](https://user-images.githubusercontent.com/24429001/42252384-e6a5bd4c-7f6e-11e8-8c88-58b7656f8689.png)

**Comment by PerpetualSmile** [comment]
windows下没有这个问题，在Linux下试了下确实有这个问题，可能是涂色的时候底层调用不同，我改了一下画法，现在没有这个问题了，你可以再试下。

**Comment by dajun928** [comment]
2.7版本 用不了么？

**Comment by AomoriL** [comment]
python 2.7.10版本是可以用的
